# This workflow is to automate Checkmarx SAST scans.  It runs on a push to the main branch.
#
# The following GitHub Secrets must be first defined:
#   - CHECKMARX_URL
#   - CHECKMARX_USER
#   - CHECKMARX_PASSWORD
#   - CHECKMARX_CLIENT_SECRET
#
# The following variables must be inserted below:
#   - <ProjectName>
#
# Update the 'team' field to reflect the team name used in Checkmarx.
#
# For full documentation, including a list of all inputs, please refer to the README https://github.com/checkmarx-ts/checkmarx-cxflow-github-action

name: Checkmarx SAST Scan
on:
  push:
    branches:
      - main
      - master
    
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Trust CX Cert
      run: echo -e "-----BEGIN CERTIFICATE-----\nMIIG4DCCBcigAwIBAgITbQAAlMAZS0rT5tBBmwAAAACUwDANBgkqhkiG9w0BAQsFADBZMRMwEQYKCZImiZPyLGQBGRYDbmV0MRQwEgYKCZImiZPyLGQBGRYEcmVnbjEUMBIGCgmSJomT8ixkARkWBHJpc2sxFjAUBgNVBAMTDU5BUERBWVBLSVAwMzkwHhcNMjEwMjA2MTUxMDQwWhcNMjIwMjA2MTUxMDQwWjCBojETMBEGCgmSJomT8ixkARkWA25ldDEUMBIGCgmSJomT8ixkARkWBHJlZ24xFDASBgoJkiaJk/IsZAEZFgRyaXNrMRAwDgYDVQQLEwdTZXJ2ZXJzMScwJQYDVQQLEx5UTFMtMS4yLU5UTE0tUmVzdHJpY3RlZCBMZXZlbDQxDDAKBgNVBAsTA0FMUDEWMBQGA1UEAxMNQUxBV1BDWE1HUjIwMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANV6+ws8rpyOqubL8VeMpnqLIQE67RCiXpg/0TQnsjdZY+OODHG5WpMMNf7MAsVW3Rn2oqvgDzix4wHNIyDNM5DYOyDnDpAuQJ3Qia9qmDFQhhuRIRC/8DZrbvyyYPBSukZ9Ub34+m8/LMJ6gLsf9iNR94ZdkeqMDg1rVJPEo6eOFiYrIu9qgNXZSKqwjJXrKKfxjmm13amEPp2pfg4xWCelQ+EquEkwY2H2YMKG1X/+blwqsBNBpKUUbIAqluHZ7/l6DbS4jAqTXgUi9QHbsS0ROnedZcWfPRsVHh3roCjVGsxsls6132oo3xTv8EDYoga6ucilKkemnEBLeKXrrpMCAwEAAaOCA1UwggNRMD4GCSsGAQQBgjcVBwQxMC8GJysGAQQBgjcVCIGDhWaB8ukQhuWdGoXi9VqC58YUgT2G281rh//qGQIBZAIBCzAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwCwYDVR0PBAQDAgWgMCcGCSsGAQQBgjcVCgQaMBgwCgYIKwYBBQUHAwEwCgYIKwYBBQUHAwIwJgYDVR0RBB8wHYIbQUxBV1BDWE1HUjIwMS5yaXNrLnJlZ24ubmV0MB0GA1UdDgQWBBSGk6iqZ/VdyERd/37rn7ZMvkgVgDAfBgNVHSMEGDAWgBSc4J1AW5ldTPH84wyDRzJC4O6CejCCAQMGA1UdHwSB+zCB+DCB9aCB8qCB74aBt2xkYXA6Ly8vQ049TkFQREFZUEtJUDAzOSxDTj1OQVBEQVlQS0lQMDM5LENOPUNEUCxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNlcyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERDPXJlZ24sREM9bmV0P2NlcnRpZmljYXRlUmV2b2NhdGlvbkxpc3Q/YmFzZT9vYmplY3RDbGFzcz1jUkxEaXN0cmlidXRpb25Qb2ludIYzaHR0cDovL3BraS5yZWVkZWxzZXZpZXIuY29tL2NlcnRzL05BUERBWVBLSVAwMzkuY3JsMIIBSQYIKwYBBQUHAQEEggE7MIIBNzCBqQYIKwYBBQUHMAKGgZxsZGFwOi8vL0NOPU5BUERBWVBLSVAwMzksQ049QUlBLENOPVB1YmxpYyUyMEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9cmVnbixEQz1uZXQ/Y0FDZXJ0aWZpY2F0ZT9iYXNlP29iamVjdENsYXNzPWNlcnRpZmljYXRpb25BdXRob3JpdHkwWwYIKwYBBQUHMAKGT2h0dHA6Ly9wa2kucmVlZGVsc2V2aWVyLmNvbS9jZXJ0cy9OQVBEQVlQS0lQMDM5LnJpc2sucmVnbi5uZXRfTkFQREFZUEtJUDAzOS5jcnQwLAYIKwYBBQUHMAGGIGh0dHA6Ly9wa2kucmVlZGVsc2V2aWVyLmNvbS9vY3NwMA0GCSqGSIb3DQEBCwUAA4IBAQCp/ktPmEGPG+0jLGc2EvTEU6tQe4/1jPbea4XGehOm8s/vNDo8VXIwuQxdNiZfm60WNwdVcjI6xUnpqSWXoRPK3snhNHMbtRcPszoUxeFxwHDF/oq7CHiqnQH8ydUCPYXovsn4GKIeyXgMemWdoFsCab5rGCH4WegrppNKbe49UwB0gJ93MbUJVPDbncvoAaXjPDDWFhthNBonlbdgMii9+m/oinbHzzTVjPXf6q6zwlJTds9xM9NKx04oYJjZASH/b4u9uQ2fjTQjroTD/KHIouqNCG6BLLGmoi8zm5ctB+mDG5b5qp1IxNrfHhrI6crMT/4bwJuJGuOdx5hKkQ4D\n-----END CERTIFICATE-----" > localcert.cert; keytool -import -trustcacerts -alias localca -file localcert.cert -keystore $JAVA_HOME/lib/security/cacerts -storepass changeit -noprompt
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.1 #Github Action version
      with:
        project: Project-GITHUB-sample # <-- Insert Checkmarx SAST Project Name
        team: ${{ secrets.CHECKMARX_TEAM }}  #To be stored in GitHub Secrets.
        checkmarx_url: ${{ secrets.CHECKMARX_URL }} # To be stored in GitHub Secrets.
        checkmarx_username: ${{ secrets.CHECKMARX_USERNAME }} # To be stored in GitHub Secrets.
        checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }} # To be stored in GitHub Secrets.
        checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }} # To be stored in GitHub Secrets.
        break_build: false
        scanners: sast
        bug_tracker: Sarif
        params: --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref }}
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: cx.sarif
